# Generated by Django 4.2.6 on 2023-10-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_period_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
